Quick Pay -> Quick Pay on Poll
centrapay/centrapay-docs pull request #392
Opened 2022-04-13 03:43 UTC by AndyClifford

Updated Quick Pay documentation to be Quick Pay on Poll. Instead of Quick Paying on creation of the payment request, we now Quick Pay the first time a payment request is polled

2022-04-13 03:48 UTC, AndyClifford commented on src/api/payment-requests/payment-requests.md
> -| Status |                  Code                  |                                                                                        Description
reformatted table

2022-04-13 21:22 UTC, Ray2126 requested changes

2022-04-13 21:22 UTC, Ray2126 commented on src/api/payment-requests/payment-requests.md
> -| 403    | {% break _ INSUFFICIENT_ASSET_VALUE %} | The asset has insufficient funds to pay the payment request or the transaction amount received by Centrapay is less than the total of the payment.
I believe this error code is still possible from the pay route.

2022-04-13 21:22 UTC, Ray2126 commented on src/guides/payment-flows.md
> +Quick Pay on Poll is used to pay the payment request immediately after it is polled for the first time, without requiring patron approval.
Think this line reads better without "immediately". What do you think?

2022-04-14 00:51 UTC, Ray2126 approved these changes

2022-04-14 02:10 UTC, merged