add docs for list asset activities endpoint
centrapay/centrapay-docs pull request #953
Opened 2023-12-08 00:10 UTC by bpal938

This adds docs for the new list asset activities endpoint
![image](https://github.com/centrapay/centrapay-docs/assets/69737582/6247644c-d1ea-489f-aee1-f3bf41f011fc)
![image](https://github.com/centrapay/centrapay-docs/assets/69737582/ec11c704-f4ca-4fa6-8c82-bd9612870313)
![image](https://github.com/centrapay/centrapay-docs/assets/69737582/d7ab650b-06bf-4cd0-a5ef-9e7a98368078)

2023-12-10 21:44 UTC, Ray2126 approved these changes

2023-12-11 03:21 UTC, bpal938 commented on src/content/api/assets.mdx
> +| token                   | [Token](#token-model) was refunded                                                                                 |
Yes token type does mean refund. It used to be used for both refund and redemption but a seperate activity has since been added for redemption

2023-12-11 21:10 UTC, Neeraj-Ghodla requested changes

2023-12-11 21:10 UTC, Neeraj-Ghodla commented on src/content/api/assets.mdx
> -<Endpoint
I would suggest keeping the list transactions endpoint in this file as it falls under the `/api/assets prefix`.

2023-12-11 21:11 UTC, Neeraj-Ghodla approved these changes

2023-12-12 20:06 UTC, merged